import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./global2.css"
import { TopBar } from "@/components/TopBar";
import  Navbar  from "@/components/NavBar";
import Footer from "@/components/Footer";
import AosProvider from "@/components/utils/AosProvider";
import { Fraunces, Inter } from "next/font/google";
import { Toaster } from "sonner";
import { AuthProvider } from "@/Provider/AuthProvider";

const fontDisplay = Fraunces({ subsets: ["latin"], variable: "--font-display" });
const fontBody = Inter({ subsets: ["latin"], variable: "--font-body" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${fontDisplay.variable} ${fontBody.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
        <AosProvider/>
        <TopBar />
        <Navbar />
        {children}
        
        <Toaster
          position="top-center"
          richColors
        
          />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
